# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Tag
    type: string

variables:
  acrName: azurearcfork8sdev
  sonobuoyVersion: 0.55.1

steps:
  - task: Docker@2
    displayName: "Build Conformance Tests"
    inputs:
      containerRegistry: "$(acrName)"
      repository: "microsoft-flux-conformance"
      command: "build"
      arguments: --build-arg SONOBUOY_VERSION="$(sonobuoyVersion)"
      tags: |
        $(Build.BuildId)
        ${{ parameters.Tag }}
        latest
  - task: Docker@2
    displayName: "Pish Conformance Tests"
    inputs:
      containerRegistry: "$(acrName)"
      repository: "microsoft-flux-conformance"
      command: "push"
      tags: |
        $(Build.BuildId)
        ${{ parameters.Tag }}
        latest
